package menuutama;

import LoginAdmin.Login;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.util.HashMap;
import java.util.Locale;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Neubri
 */
public class MenuUtama extends javax.swing.JFrame {
    private Connection conn = (Connection) new Koneksi().connect();

    Color hoverButton;

    /**
     * Creates new form NewJFrame
     */
    public MenuUtama() {
        initComponents();
        Locale locale = Locale.forLanguageTag("id-ID");
        Locale.setDefault(locale);
        setVisible(true);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        slideMenuPengaturan.setVisible(true);
        slideMenuLaporan.setVisible(true);
        Menu.repaint();
        Menu.revalidate();
        this.hoverButton = dataMotor.getBackground();
        Pane.add(Home);
        Pane.repaint();
        Pane.revalidate();
    }

    private void hiddenSubMenu() {
        if (slideMenuLaporan.isVisible() == true) {
            slideMenuLaporan.setVisible(false);
            slideMenuPengaturan.setVisible(false);
        }
        if (slideMenuPengaturan.isVisible() == true) {
            slideMenuLaporan.setVisible(false);
            slideMenuPengaturan.setVisible(false);
        }
    }

    private void showSubMenu(JPanel subMenu) {
        // Only allow toggling for other submenus, not for slideMenuPengaturan or
        // slideMenuLaporan
        if (subMenu == slideMenuPengaturan) {
            slideMenuPengaturan.setVisible(true);
        } else if (subMenu == slideMenuLaporan) {
            slideMenuLaporan.setVisible(true);
        } else {
            if (!subMenu.isVisible()) {
                hiddenSubMenu();
                subMenu.setVisible(true);
            } else {
                subMenu.setVisible(false);
            }
        }
    }

    // akhis slider menu
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        dataMotor = new javax.swing.JLabel();
        kriteria = new javax.swing.JLabel();
        slideMenuLaporan = new javax.swing.JPanel();
        laporanDataMotor = new javax.swing.JLabel();
        laporanPrioritasKriteria = new javax.swing.JLabel();
        laporanPrioritasSubKriteria = new javax.swing.JLabel();
        laporanHasilSeleksi = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        slideMenuPengaturan = new javax.swing.JPanel();
        menuPengaturanKriteria = new javax.swing.JLabel();
        menuPengaturanSubKriteria = new javax.swing.JLabel();
        seleksi = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        Pane = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();

        Home.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang, di Aplikasi");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Pendukung Keputusan Pemilihan Motor Matic Roda Dua ");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menggunakan Metode AHP");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
                HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        HomeLayout.setVerticalGroup(
                HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HomeLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(551, Short.MAX_VALUE)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 1200));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setMaximumSize(new java.awt.Dimension(32767, 600));

        dataMotor.setBackground(new java.awt.Color(0, 0, 51));
        dataMotor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dataMotor.setForeground(new java.awt.Color(255, 255, 255));
        dataMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataMotor.setText("MOTOR");
        dataMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataMotor.setOpaque(true);
        dataMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMotorMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataMotorMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataMotorMouseExited(evt);
            }
        });

        kriteria.setBackground(new java.awt.Color(0, 0, 51));
        kriteria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        kriteria.setForeground(new java.awt.Color(255, 255, 255));
        kriteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (7).png"))); // NOI18N
        kriteria.setText("KRITERIA");
        kriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kriteria.setOpaque(true);
        kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kriteriaMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kriteriaMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                kriteriaMouseExited(evt);
            }
        });

        slideMenuLaporan.setBackground(new java.awt.Color(80, 80, 80));
        slideMenuLaporan.setForeground(new java.awt.Color(255, 255, 255));

        laporanDataMotor.setBackground(new java.awt.Color(51, 51, 51));
        laporanDataMotor.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        laporanDataMotor.setForeground(new java.awt.Color(255, 255, 255));
        laporanDataMotor.setText("    Laporan Motor ");
        laporanDataMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanDataMotor.setOpaque(true);
        laporanDataMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanDataMotorMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanDataMotorMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanDataMotorMouseExited(evt);
            }
        });

        laporanPrioritasKriteria.setBackground(new java.awt.Color(51, 51, 51));
        laporanPrioritasKriteria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        laporanPrioritasKriteria.setForeground(new java.awt.Color(255, 255, 255));
        laporanPrioritasKriteria.setText("    Laporan Prioritas Kriteria");
        laporanPrioritasKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanPrioritasKriteria.setOpaque(true);
        laporanPrioritasKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseExited(evt);
            }
        });

        laporanPrioritasSubKriteria.setBackground(new java.awt.Color(51, 51, 51));
        laporanPrioritasSubKriteria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        laporanPrioritasSubKriteria.setForeground(new java.awt.Color(255, 255, 255));
        laporanPrioritasSubKriteria.setText("    Laporan Prioritas SubKriteria");
        laporanPrioritasSubKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanPrioritasSubKriteria.setOpaque(true);
        laporanPrioritasSubKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPrioritasSubKriteriaMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPrioritasSubKriteriaMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPrioritasSubKriteriaMouseExited(evt);
            }
        });

        laporanHasilSeleksi.setBackground(new java.awt.Color(51, 51, 51));
        laporanHasilSeleksi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        laporanHasilSeleksi.setForeground(new java.awt.Color(255, 255, 255));
        laporanHasilSeleksi.setText("    Laporan Hasil Seleksi");
        laporanHasilSeleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanHasilSeleksi.setOpaque(true);
        laporanHasilSeleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuLaporanLayout = new javax.swing.GroupLayout(slideMenuLaporan);
        slideMenuLaporan.setLayout(slideMenuLaporanLayout);
        slideMenuLaporanLayout.setHorizontalGroup(
                slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(laporanDataMotor, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(laporanPrioritasSubKriteria, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        slideMenuLaporanLayout.setVerticalGroup(
                slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(slideMenuLaporanLayout.createSequentialGroup()
                                .addComponent(laporanDataMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laporanPrioritasSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        laporan.setBackground(new java.awt.Color(0, 0, 51));
        laporan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (13).png"))); // NOI18N
        laporan.setText("LAPORAN");
        laporan.setOpaque(true);
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        slideMenuPengaturan.setBackground(new java.awt.Color(255, 255, 255));
        slideMenuPengaturan.setForeground(new java.awt.Color(255, 255, 255));

        menuPengaturanKriteria.setBackground(new java.awt.Color(51, 51, 51));
        menuPengaturanKriteria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuPengaturanKriteria.setForeground(new java.awt.Color(255, 255, 255));
        menuPengaturanKriteria.setText(" Pengaturan Prioritas Kriteria");
        menuPengaturanKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPengaturanKriteria.setOpaque(true);
        menuPengaturanKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPengaturanKriteriaMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPengaturanKriteriaMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPengaturanKriteriaMouseExited(evt);
            }
        });

        menuPengaturanSubKriteria.setBackground(new java.awt.Color(51, 51, 51));
        menuPengaturanSubKriteria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuPengaturanSubKriteria.setForeground(new java.awt.Color(255, 255, 255));
        menuPengaturanSubKriteria.setText(" Pengaturan Prioritas SubKriteria");
        menuPengaturanSubKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPengaturanSubKriteria.setOpaque(true);
        menuPengaturanSubKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPengaturanSubKriteriaMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPengaturanSubKriteriaMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPengaturanSubKriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuPengaturanLayout = new javax.swing.GroupLayout(slideMenuPengaturan);
        slideMenuPengaturan.setLayout(slideMenuPengaturanLayout);
        slideMenuPengaturanLayout.setHorizontalGroup(
                slideMenuPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuPengaturanKriteria, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuPengaturanSubKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 192,
                                Short.MAX_VALUE));
        slideMenuPengaturanLayout.setVerticalGroup(
                slideMenuPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(slideMenuPengaturanLayout.createSequentialGroup()
                                .addComponent(menuPengaturanKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuPengaturanSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        seleksi.setBackground(new java.awt.Color(0, 0, 51));
        seleksi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        seleksi.setForeground(new java.awt.Color(255, 255, 255));
        seleksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (9).png"))); // NOI18N
        seleksi.setText("SELEKSI");
        seleksi.setOpaque(true);
        seleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleksiMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleksiMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(slideMenuPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seleksi, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(slideMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataMotor, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kriteria, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        MenuLayout.setVerticalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(dataMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slideMenuPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(seleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slideMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        judul1.setBackground(new java.awt.Color(255, 0, 0));
        judul1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image (1).png"))); // NOI18N
        judul1.setText("   Sistem Pendukung Keputusan Pemilihan Motor matic roda dua");
        judul1.setOpaque(true);

        Pane.setBackground(new java.awt.Color(204, 204, 204));
        Pane.setMaximumSize(new java.awt.Dimension(1200, 650));
        Pane.setMinimumSize(new java.awt.Dimension(380, 200));
        Pane.setPreferredSize(new java.awt.Dimension(600, 570));
        Pane.setLayout(new java.awt.CardLayout());

        logout.setBackground(new java.awt.Color(0, 0, 51));
        logout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOG OUT");
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 192,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(judul1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(Color.BLACK);
    }// GEN-LAST:event_logoutMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(51, 51, 51));
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_logoutMouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }// GEN-LAST:event_logoutMouseClicked

    private void seleksiMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_seleksiMouseExited
        // TODO add your handling code here:
        seleksi.setBackground(hoverButton);
    }// GEN-LAST:event_seleksiMouseExited

    private void seleksiMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_seleksiMouseEntered
        // TODO add your handling code here:
        seleksi.setBackground(new Color(51, 51, 51));
        seleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_seleksiMouseEntered

    private void seleksiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_seleksiMouseClicked
        // TODO add your handling code here:
        // remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new Seleksi());
        Pane.repaint();
        Pane.revalidate();
    }// GEN-LAST:event_seleksiMouseClicked

    private void menuPengaturanSubKriteriaMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuPengaturanSubKriteriaMouseExited
        // TODO add your handling code here:
        menuPengaturanSubKriteria.setBackground(new Color(80, 80, 80));
    }// GEN-LAST:event_menuPengaturanSubKriteriaMouseExited

    private void menuPengaturanSubKriteriaMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuPengaturanSubKriteriaMouseEntered
        // TODO add your handling code here:
        menuPengaturanSubKriteria.setBackground(new Color(51, 51, 51));
        menuPengaturanSubKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_menuPengaturanSubKriteriaMouseEntered

    private void menuPengaturanSubKriteriaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuPengaturanSubKriteriaMouseClicked
        // TODO add your handling code here:
        // remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new PengaturanSubKriteria());
        Pane.repaint();
        Pane.revalidate();
    }// GEN-LAST:event_menuPengaturanSubKriteriaMouseClicked

    private void menuPengaturanKriteriaMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuPengaturanKriteriaMouseExited
        // TODO add your handling code here:
        menuPengaturanKriteria.setBackground(new Color(80, 80, 80));
    }// GEN-LAST:event_menuPengaturanKriteriaMouseExited

    private void menuPengaturanKriteriaMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuPengaturanKriteriaMouseEntered
        // TODO add your handling code here:
        menuPengaturanKriteria.setBackground(new Color(51, 51, 51));
        menuPengaturanKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_menuPengaturanKriteriaMouseEntered

    private void menuPengaturanKriteriaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menuPengaturanKriteriaMouseClicked
        // TODO add your handling code here:
        // remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new PengaturanKriteria());
        Pane.repaint();
        Pane.revalidate();
    }// GEN-LAST:event_menuPengaturanKriteriaMouseClicked

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanMouseExited
        // TODO add your handling code here:
        laporan.setBackground(hoverButton);
    }// GEN-LAST:event_laporanMouseExited

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanMouseEntered
        // TODO add your handling code here:
        laporan.setBackground(new Color(51, 51, 51));
        laporan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_laporanMouseEntered

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanMouseClicked
        // Do nothing, submenu is always visible
    }// GEN-LAST:event_laporanMouseClicked

    private void laporanHasilSeleksiMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanHasilSeleksiMouseExited
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(80, 80, 80));
    }// GEN-LAST:event_laporanHasilSeleksiMouseExited

    private void laporanHasilSeleksiMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanHasilSeleksiMouseEntered
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(51, 51, 51));
        laporanHasilSeleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_laporanHasilSeleksiMouseEntered

    private void laporanHasilSeleksiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanHasilSeleksiMouseClicked
        // TODO add your handling code here:
        try {
            String report = "./src/laporan/LaporanHasilSeleksi.jasper";
            HashMap<String, Object> param = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(report, param, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }// GEN-LAST:event_laporanHasilSeleksiMouseClicked

    private void laporanPrioritasSubKriteriaMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanPrioritasSubKriteriaMouseExited
        // TODO add your handling code here:
        laporanPrioritasSubKriteria.setBackground(new Color(80, 80, 80));
    }// GEN-LAST:event_laporanPrioritasSubKriteriaMouseExited

    private void laporanPrioritasSubKriteriaMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanPrioritasSubKriteriaMouseEntered
        // TODO add your handling code here:
        laporanPrioritasSubKriteria.setBackground(new Color(51, 51, 51));
        laporanPrioritasSubKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_laporanPrioritasSubKriteriaMouseEntered

    private void laporanPrioritasSubKriteriaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanPrioritasSubKriteriaMouseClicked
        // TODO add your handling code here:

        try {
            String report = "./src/laporan/LaporanPrioritasSubKriteria.jasper";
            HashMap<String, Object> param = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(report, param, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }// GEN-LAST:event_laporanPrioritasSubKriteriaMouseClicked

    private void laporanPrioritasKriteriaMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanPrioritasKriteriaMouseExited
        // TODO add your handling code here:
        laporanPrioritasKriteria.setBackground(new Color(80, 80, 80));
    }// GEN-LAST:event_laporanPrioritasKriteriaMouseExited

    private void laporanPrioritasKriteriaMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanPrioritasKriteriaMouseEntered
        // TODO add your handling code here:
        laporanPrioritasKriteria.setBackground(new Color(51, 51, 51));
        laporanPrioritasKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_laporanPrioritasKriteriaMouseEntered

    private void laporanPrioritasKriteriaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanPrioritasKriteriaMouseClicked
        // TODO add your handling code here:
        try {
            String report = "./src/laporan/LaporanPrioritasKriteria.jasper";
            HashMap<String, Object> param = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(report, param, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }// GEN-LAST:event_laporanPrioritasKriteriaMouseClicked

    private void laporanDataMotorMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanDataMotorMouseExited
        // TODO add your handling code here:
        laporanDataMotor.setBackground(new Color(80, 80, 80));
    }// GEN-LAST:event_laporanDataMotorMouseExited

    private void laporanDataMotorMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanDataMotorMouseEntered
        // TODO add your handling code here:
        laporanDataMotor.setBackground(new Color(51, 51, 51));
        laporanDataMotor.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_laporanDataMotorMouseEntered

    private void laporanDataMotorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_laporanDataMotorMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuPengaturan);
        try {
            String report = "./src/laporan/LaporanDataMotor.jasper";
            HashMap<String, Object> param = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(report, param, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }// GEN-LAST:event_laporanDataMotorMouseClicked

    private void kriteriaMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kriteriaMouseExited
        // TODO add your handling code here:
        kriteria.setBackground(hoverButton);
    }// GEN-LAST:event_kriteriaMouseExited

    private void kriteriaMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kriteriaMouseEntered
        // TODO add your handling code here:
        kriteria.setBackground(new Color(51, 51, 51));
        kriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_kriteriaMouseEntered

    private void kriteriaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kriteriaMouseClicked
        // Do nothing, submenu is always visible
    }// GEN-LAST:event_kriteriaMouseClicked

    private void dataMotorMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dataMotorMouseExited
        // TODO add your handling code here:
        dataMotor.setBackground(hoverButton);
    }// GEN-LAST:event_dataMotorMouseExited

    private void dataMotorMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dataMotorMouseEntered
        // TODO add your handling code here:
        dataMotor.setBackground(new Color(51, 51, 51));
        dataMotor.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }// GEN-LAST:event_dataMotorMouseEntered

    private void dataMotorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dataMotorMouseClicked
        // TODO add your handling code here:
        // remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new DataMotor());
        Pane.repaint();
        Pane.revalidate();
    }// GEN-LAST:event_dataMotorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Pane;
    private javax.swing.JLabel dataMotor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel kriteria;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel laporanDataMotor;
    private javax.swing.JLabel laporanHasilSeleksi;
    private javax.swing.JLabel laporanPrioritasKriteria;
    private javax.swing.JLabel laporanPrioritasSubKriteria;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menuPengaturanKriteria;
    private javax.swing.JLabel menuPengaturanSubKriteria;
    private javax.swing.JLabel seleksi;
    private javax.swing.JPanel slideMenuLaporan;
    private javax.swing.JPanel slideMenuPengaturan;
    // End of variables declaration//GEN-END:variables
}
